### PR TITLE
PAMPA toolsuite : Trying to improve lint R

### PR DESCRIPTION
**Pull request by ColineRoyaux**
Still can't figure out how to handle 'no visible global function definition for' warnings for functions not developped in a R package (with source code in FunctPAMPAGalaxy.r)

### CODE REVIEW

**Comment by bgruening** [comment]
@ColineRoyaux does that help? https://rdrr.io/cran/lintr/man/exclude.html

**Comment by ColineRoyaux** [comment]
@bgruening thank you very much ! I'm not sure how to apply this function, I made a small try to see if I did it right

**Comment by ColineRoyaux** [comment]
@bgruening It seems okay ! Thank you again ! Hope I didn't do anything wrong

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
@ColineRoyaux does this linting help you? Does it improve the code or is that more annoying? 

Please go ahead and let's get this tool published in the ToolShed :)

Thanks a lot!

**Comment by ColineRoyaux** [comment]
@bgruening I'd say it helps a lot to get a clean code ! And most importantly a code that will be easier to understand for others. 
It took me maybe two or three days at most to make the proper modifications and most of this time I was searching how to deal with the 'no visible global function definition for' warnings so, from now on i'd say it wouldn't take more than a few hours to get a way better code !

**Comment by yvanlebras** [comment]
Thank you so much wonder Coline !! And wonder Björn !!!!!!!!

Now the lintr is ok, it seems that there is an issue no the github action / ci /planemo action:
```
 Error: Invalid value for '--exclude_from': File '.tt_biocontainer_skip' does not exist.
```
Any idea @bgruening ? Or maybe just a transient issue (or maybe not important ;) ) ?

**Comment by bgruening** [comment]
please add an empty .tt_biocontainer_skip file to the base of this repo.

**Comment by bgruening** [comment]
If have done this now, let's see if its works now.

**Comment by yvanlebras** [comment]
Thanks! Will see

**Pull request merged**
