### PR TITLE
Timeseries tool

### PR DESCRIPTION
**Pull request by Quickbeasts51429**
Added time-series extraction tool.

### CODE REVIEW

**Comment by annefou** [comment]
@bgruening 
> @Quickbeasts51429 very nice. Can you please add a shed.yml file?

We put everything we xarray tools. Also updating all xarray tools with the latest Python packages.

**Comment by bgruening** [comment]
Tests seem to fail with: `Output collection 'output_dir': expected to have 5 elements, but it had 0.`

**Comment by annefou** [comment]
> Tests seem to fail with: `Output collection 'output_dir': expected to have 5 elements, but it had 0.`

Ok. I will look at it. I probably messed up somewhere! Thanks a lot for pointing the error.

**Comment by annefou** [comment]
> Tests seem to fail with: `Output collection 'output_dir': expected to have 5 elements, but it had 0.`

@bgruening I think I finally understood what was wrong! I was trying to use a version of geopandas from conda-forge that is in `cf-staging` (for some reasons most of the geopandas versions are in cf-staging mode).

**Comment by bgruening** [comment]
Oh, that is unfortunate ... should we create a container?

**Comment by annefou** [comment]
> Oh, that is unfortunate ... should we create a container?

What do you mean? Sorry, I don't get it!

**Comment by annefou** [comment]
> If you really need the new version we can create a container and not use condor.

No we don't need a new version. It is not important. Thanks.

**Review by bgruening — APPROVED** [review]
LGTM!

**Pull request merged**
