### PR TITLE
update officer

### PR DESCRIPTION
**Pull request by Marie59**

### CODE REVIEW

**Comment by bgruening** [comment]
Oo, R again? Do you need help here?

**Comment by Marie59** [comment]
> Oo, R again? Do you need help here?

Yes ... I don't understand what went wrong there. I tried multiple things but it does not seem to be helping and don't really have more ideas on what to do for now.

**Comment by bgruening** [comment]
What was the initial aim of this PR?

**Comment by Marie59** [comment]
The ivr tool was not working anymore on galaxy ecology. So I tried to see what was the issue and fix it

**Comment by bgruening** [comment]
Can you sent a bug report about the failure?

**Comment by Marie59** [comment]
image001

This is the issue.

**Comment by bgruening** [comment]
Ok, what is the tool ID?

**Comment by Marie59** [comment]
I tried on EU it is a bit better but i still have an error :
Capture d’écran du 2023-02-21 09-20-50

**Comment by yvanlebras** [comment]
seems to be an error with pandoc, so appparently related to an error with r-rmarkdown dependancy.

**Comment by yvanlebras** [comment]
It seems this is better for ivr, the fail seems to be due to file access right error:

**Comment by yvanlebras** [comment]
For cb_div, it seems there is an issue with rgl, maybe due to dplyr dependency issue??
```
Error in dyn.load(dynlib <- getDynlib(dir)) : 
  unable to load shared object '/usr/local/lib/R/library/rgl/libs/rgl.so':
  libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by yvanlebras** [comment]
Ok, so now on cb_div, we have this error:
```
Job in error state.. tool_id: cb_div, exit_code: 1, stderr: Error in library(magrittr) : there is no package called âmagrittrâ
Execution halted
```
And adding r-magrittr dependency is not working for now....

**Comment by yvanlebras** [comment]
I am asking myself if there is not a missing element on div_index.xml to load macros requirements through <expand macro="cb_requirements"> ? Or it is normal to not load these cb requirements? And on the macros XML file, in cb_requirements tag, this is normal to have the yield tag? This allows to combine macros + tool XML specific requirements?

**Comment by Marie59** [comment]
> I am asking myself if there is not a missing element on div_index.xml to load macros requirements through ? Or it is normal to not load these cb requirements? And on the macros XML file, in cb_requirements tag, this is normal to have the yield tag? This allows to combine macros + tool XML specific requirements?

I remove the cb_requirements from this tool to test if there was not a conflict there. I did not put it back because I noticed that multiple of the cb_requirements were useless in cb_div.
I don't really know what the yield tag does I put it by habit. 
Could the issue come from a conflict between adiv and dplyr ?

**Comment by yvanlebras** [comment]
ok. thank you for your reply! My test on replacing dplyr by tidyverse was not successfull...  I don't think there is a conflict between adiv and dplyr...

**Comment by yvanlebras** [comment]
for  "cb_ivr_site_report_col_scale_loop.knitr.Rmd", is it a file we normally need to have as input or this is generated from " <include "cb_ivr_site_report_col_scale_loop.Rmd" ?

**Comment by Marie59** [comment]
> for "cb_ivr_site_report_col_scale_loop.knitr.Rmd", is it a file we normally need to have as input or this is generated from " <include "cb_ivr_site_report_col_scale_loop.Rmd" ?

It's generated from  "cb_ivr_site_report_col_scale_loop.Rmd"

**Comment by yvanlebras** [comment]
ok. This read-only file system error seems to me maybe due to an issue on the Github filesystem, but can be ok on usegalaxy.eu. What do you think about it @bgruening ?
As a reminder,the error on the stderr is:
```
7: In file(con, "w") :
  cannot open file 'cb_ivr_site_report_col_scale_loop.knit.md': Read-only file system
Execution halted
```

**Comment by yvanlebras** [comment]
Hmmm . Really strange. I was using planemo since 2 days to go forward on these tools, and planemo is ok for cb_ivr and div_index locally (with a fresh planemo installation). Do you have an idea @bgruening ? If ok on a fresh intalaltion of planemo, this seems normally it is ok no ?

**Comment by yvanlebras** [comment]
For information
here for ivr, the issue is related to this 
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace âofficerâ 0.4.4 is already loaded, but >= 0.5.1 is required
```
(but it works on planemo locally...)

for cb_div, here is the issue
```
Job in error state.. tool_id: cb_div, exit_code: 1, stderr: Error in library(dplyr) : there is no package called âdplyrâ
```
but locally it is ok on planemo....

**Comment by bgruening** [comment]
> processing file: cb_ivr_site_report_col_scale_loop.Rmd
Error in file(con, "w") : cannot open the connection
Calls: source ... <Anonymous> -> <Anonymous> -> write_utf8 -> writeLines -> file
In addition: Warning messages:
1: In do_once((if (is_R_CMD_check()) stop else warning)("The function xfun::isFALSE() will be deprecated in the future. Please ",  :
  The function xfun::isFALSE() will be deprecated in the future. Please consider using base::isFALSE(x) or identical(x, FALSE) instead.
2: In min(df1$ivr.med, na.rm = T) :
  no non-missing arguments to min; returning Inf
3: In max(df1$ivr.med, na.rm = T) :
  no non-missing arguments to max; returning -Inf
4: In min(df1$ivr.min, na.rm = T) :
  no non-missing arguments to min; returning Inf
5: In max(df1$ivr.max, na.rm = T) :
  no non-missing arguments to max; returning -Inf
6: In min(unique(df1$Annee), na.rm = T) :
  no non-missing arguments to min; returning Inf
7: In max(unique(df1$Annee), na.rm = T) :
  no non-missing arguments to max; returning -Inf
8: In file(con, "w") :
  cannot open file 'cb_ivr_site_report_col_scale_loop.knit.md': Read-only file system
Execution halted
.


Was the latest error.

**Comment by bgruening** [comment]
Lessons learned, please remind me that if we deal with `rgl` or any other GL library, we need to build an extended container, since the default biocontainer does not ship libGL.so.

Please remind me on that next time :)

**Comment by Marie59** [comment]
Oh amazing !! Thanks a lot @bgruening and @yvanlebras !!

**Pull request merged**
