### PR TITLE
Reactivate to look at xmlstarlet ci errors

### PR DESCRIPTION
**Pull request by yvanlebras**

### CODE REVIEW

**Comment by yvanlebras** [comment]
Ok @bgruening I check ci wf all results and it appears there was a space after the test filename and before the " sign ;) hope this is just this! Have an amazing week end!!!!!

**Comment by bgruening** [comment]
> xmlstarlet: command not found

Hu?

**Comment by bgruening** [comment]
ok, now it at least works, but your test data needs an update:

```
Output output:  different than expected, difference (using diff):
( /tmp/tmppe5kobv7output_standardEML.xml v. /tmp/tmpp0qiemcuoutput_standardEML.xml )
--- local_file
+++ history_data
@@ -51,12 +51,12 @@
       <!--No geographic description provided-->
       <!--Geographic coverage-->
       <geographicCoverage>
-        <geographicDescription>Massif des PyrÃ©nÃ©es</geographicDescription>
+        <geographicDescription>No geographic description provided.</geographicDescription>
         <boundingCoordinates>
-          <westBoundingCoordinate>-1,7055252</westBoundingCoordinate>
-          <eastBoundingCoordinate>3,1811955</eastBoundingCoordinate>
-          <northBoundingCoordinate>43,5254599</northBoundingCoordinate>
-          <southBoundingCoordinate>42,2299506</southBoundingCoordinate>
+          <westBoundingCoordinate>311090.112199999</westBoundingCoordinate>
+          <eastBoundingCoordinate>714654.00</eastBoundingCoordinate>
+          <northBoundingCoordinate>6269615.00</northBoundingCoordinate>
+          <southBoundingCoordinate>6137120.9254</southBoundingCoordinate>
         </boundingCoordinates>
       </geographicCoverage>
       <!--Temporal coverage-->
@@ -86,159 +86,5 @@
       <phone>(+33)561285516</phone>
       <electronicMailAddress>wilfried.heintz@inrae.fr</electronicMailAddress>
     </contact>
-    <spatialVector
********
*SNIP *
********
-                name="standard_parallel_1"
-                value="44"/>
-              <parameter
-                name="standard_parallel_2"
-                value="49"/>
-              <parameter
-                name="false_easting"
-                value="700000"/>
-              <parameter
-                name="false_northing"
-                value="6600000"/>
-              <unit name="meter"/>
-            </projection>
-          </projCoordSys>
-        </horizCoordSysDef>
-      </spatialReference>
-      <horizontalAccuracy>
-        <accuracyReport>Unknown</accuracyReport>
-      </horizontalAccuracy>
-      <verticalAccuracy>
-        <accuracyReport>Unknown</accuracyReport>
-      </verticalAccuracy>
-    </spatialVector>
   </dataset>
 </eml:eml>
```

**Comment by bgruening** [comment]
@yvanlebras https://github.com/galaxyecology/tools-ecology/pull/55/commits/5d642b671a1c118ae1e31de64bb8883ae11269b5 fixes the test but you should really check if the result is correct.

**Comment by yvanlebras** [comment]
Thank you Björn! But this is strange that in output test file for example the script is not finding "title" as there is a "gco:CharacterString" info in the input test file... I need to check more into detail...

**Comment by yvanlebras** [comment]
Just checked! Test data were not the good one compared to the one I used to develop the tool with my local planemo... Duno why... hope this is better now!

**Comment by yvanlebras** [comment]
oh oh! Finally "super green" ;)

**Review by bgruening — APPROVED** [review]

**Pull request merged**
