### PR TITLE
Fix bug xarray and extend functionalities

### PR DESCRIPTION
**Pull request by annefou**
- pass info via config file when plotting title, etc where not working properly)
- add the possibility to select by values (and not only by indices) 
- add the possibility to select several variables
- add the possibility to mask values (xarray where).

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
* please add a profile to all tools

**Comment by bgruening** [comment]
Its hard to review, as every line has changed ... so lets get it in :)

**Review by bgruening — APPROVED** [review]
lets hope the tests are sufficient :)

**Comment by annefou** [comment]
> Its hard to review, as every line has changed ... so lets get it in :)

How should I do it next time to make it easier?

**Comment by bgruening** [comment]
I think next time will be fine. You changed probably a lot of whitespaces, can this be?

**Comment by annefou** [comment]
As recommended, I installed visual studio code and galaxy  tool extension. It seems spaces and end of lines are different.

**Comment by bgruening** [comment]
I think this is all fine :)

**Comment by yvanlebras** [comment]
> * please add a profile to all tools

hmmm was not aware of that "profile" item. If I understand, this allows to specify a Galaxy version so we can look at this if there is "strange" behaviour of a tool ?

**Comment by yvanlebras** [comment]
Hey !!! Amazing Geschenk for 2022! Happy new year Anne, Björn !

Trying to deploytools to test it, I have a "Failed linting" with xarray_netcdf2netcdf.xml tool (but this can be due to an old planemo version maybe ?). Come back to you rapidly

**Comment by annefou** [comment]
> Hey !!! Amazing Geschenk for 2022! Happy new year Anne, Björn !
> 
> Trying to deploytools to test it, I have a "Failed linting" with xarray_netcdf2netcdf.xml tool (but this can be due to an old planemo version maybe ?). Come back to you rapidly
Which version are you using? I am using 0.74.9 on my computer; I am not sure which version is used in github action.
What error do you get?

**Comment by bgruening** [comment]
> > * please add a profile to all tools
> 
> hmmm was not aware of that "profile" item. If I understand, this allows to specify a Galaxy version so we can look at this if there is "strange" behaviour of a tool ?

Not really. Galaxy add new features, how it treats tools. E.g. how to handle the HOME directory or some other features that are only available in newer Galaxy version. This profile version will tell Galaxy that this tool can and wants to use those newer features. If you do not use a profile, you do not get any of those features/behaviours.

**Comment by annefou** [comment]
@yvanlebras Do you still have a "Failed linting" with xarray_netcdf2netcdf.xml tool? How can we help?

**Review by bgruening — APPROVED** [review]

**Pull request merged**
