### PR TITLE
Srs update

### PR DESCRIPTION
**Pull request by Marie59**
Fix for the bil, hdr issue in pca_raster.xml and spectral_indices.xml.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by yvanlebras** [comment]
The error on the preprocess tool seems to be "only" related to lack of memory. I think this is ok , moreover, There is no change on this tool if I am not saying a mistake

**Comment by yvanlebras** [comment]
Thank you so much Marie !!!
Is it ok for you to merge Björn ?
Good appetit!

**Comment by bgruening** [comment]
What is the test error?

**Comment by yvanlebras** [comment]
exit code 137 => issue with container resources

**Comment by bgruening** [comment]
I can merge and push locally later at the day. But we need to think about stability of those tools :-(

**Comment by yvanlebras** [comment]
Yes. This tool is using a lot of memory, and it is very hard to find small data for the test, but we definitely need to find a way having these test using less resources. On the GH actions, we can't increase resources and/or this is not so easy ?

**Comment by bgruening** [comment]
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by yvanlebras** [comment]
I see that on a 35 Mb, preprocess tool is using 41 Gb memory...

**Pull request merged**
