### PR TITLE
Add ingestor tool

### PR DESCRIPTION
**Pull request by Marie59**
Hi all, 

New tool to aggregate and harmonized the Biogeochemical data from Argo raw data and from Gliders. 
This is part of one of FAIR-EASE pilots (Ocean Biogeochemical) in which  @alban.sizun and  @clement.weber !
- I invite you to check the lats section on help see if it's okay with you. 
- Also if the name and the small description at the beginning is good enough to make the tool findable 
- And also the help line in the input is it good ?

@bgruening Is this enough for the test part ? I nerver know how much is enough. 

Let's see what crashes ! and thanks for the reviews :)

### CODE REVIEW

**Comment by bgruening** [comment]
Tests can never be enough ;-)
If roughly every conditional, input output compilation is covered it's ok. This tool LGTM! 🥳

**Comment by Marie59** [comment]
Ah @bgruening I see that the copernicus marine is making this PR bug ... can I skip the test on it for this PR ?

**Comment by Marie59** [comment]
Okay so I guess now everything that is related to this new tool is working

**Comment by detocjerome** [comment]
I guess the tool will not in charge to collect data. So call it Ingestor will cause incomprehension
I propose for Galaxy purpose to name it convert_to_bgc_netcdf

**Comment by Marie59** [comment]
> I guess the tool will not in charge to collect data. So call it Ingestor will cause incomprehension I propose for Galaxy purpose to name it convert_to_bgc_netcdf

- convert_to_bgc_netcdf would more fit for an id not a tool name let's say `id=convert_to_bgc_netcdf`
- `name=Netcdf aggregator `
(Knowing that in the tool panel whats going to be seen is: " **Netcdf aggregator** for marine biogeochemical data "

**Comment by cwebear** [comment]
Hello Marie and Jérôme, 
This tool takes in entry files of Argo or Glider data (T,S or BGC, or both) (provided by the user on galaxy) and returns this set of files harmonized (i.e renamed and variables filtered) following qcv platform convention and aggragated (i.e, all the files having different shapes, are aligned to create a single file readable as a dataset).  

For the needs of Galaxy I suggest 
id = harmonize_insitu_to_netcdf 
name = qcv_app_harmonizer
description = Harmonizer and aggregator of insitu marine physical and biogeochimical data. This tools works for Argo or Gliders datafiles following CMEMS convention. 

What do you think ?

**Comment by detocjerome** [comment]
I always have a kind of suppressed admiration for people who can get everyone to agree.
In other words **OK**
I hope you enjoy this discovery 
https://youtu.be/II1vza8955g

**Comment by detocjerome** [comment]
Otherwise, this isn't the place to say this any more than it is to share the music, but it's coming along nicely.

**Comment by Marie59** [comment]
> Hello Marie and Jérôme, This tool takes in entry files of Argo or Glider data (T,S or BGC, or both) (provided by the user on galaxy) and returns this set of files harmonized (i.e renamed and variables filtered) following qcv platform convention and aggragated (i.e, all the files having different shapes, are aligned to create a single file readable as a dataset).
> 
> For the needs of Galaxy I suggest id = harmonize_insitu_to_netcdf name = qcv_app_harmonizer description = Harmonizer and aggregator of insitu marine physical and biogeochimical data. This tools works for Argo or Gliders datafiles following CMEMS convention.
> 
> What do you think ?

All good for me @cwebear I would just change the name to sometihing more user friendly like "QCV harmonizer" ?
that way in the end the user will see 
"**QCV harmonizer** and aggregator of insitu marine physical and biogeochimical data"

**Comment by Marie59** [comment]
I am fixing my folder issue (to make something cleaner), the PR keeps going here https://github.com/galaxyecology/tools-ecology/pull/148

**Pull request closed without merging**
