### PR TITLE
Tool to convert ab1 files into fastq

### PR DESCRIPTION
**Pull request by ColineRoyaux**
This tool isn't dedicated to ecology so I didn't put any edam_topic, hope I haven't forgotten anything !

### CODE REVIEW

**Comment by bgruening** [comment]
@pvanheus that might be interesting for you as well.

**Comment by ColineRoyaux** [comment]
Hey @bgruening ! Is it anything I can do on this PR to make it work ? This tool would be very useful for my PhD thesis

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Sorry, I just dropped the ball here. Sorry.

**Comment by ColineRoyaux** [comment]
Oh no problem ! Thank you very much :)

**Pull request merged**
